default: &default
  adapter: postgresql
  encoding: latin1
  host: localhost
  pool: 10
  timeout: 5000
  username: cpb_admin

development:
  <<: *default
  database: cpb_dev

test:
  <<: *default
  database: cpb_test

production:
  <<: *default
  database: cpb_prod
