# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9536478878ea78cc90079b089f35fdf9c29d16213af710bc751bbc6d6a5dffc527981b56ccc79b9f25529d61fef43e87decf1e2ee88e4aca927b576f4967e3b4

test:
  secret_key_base: 33e4ce09ddfe4f6cf93ec3b922fffb5647bfbfaca08adefeed21c276c7d2990ddaef63e782f214aa97ab2d9f55f0a3813730b59aea02b287d09c71508c82924b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
